apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30009
  selector:
    app: result
  type: NodePort