apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30008
  selector:
    app: vote
  type: NodePort